Ambiguous spelling warning exception for "specialty"
python-discord/code-jam-qualifier-9 pull request #5
Opened 2022-06-29 21:26 UTC by ionite34

Previously discussed in #4 for the prevalence of issues regarding the mis-spelling of "speciality" in some dialects.

To preserve backward compatibility with existing checks, this proposal adds a special `RuntimeError` message that is raise whenever access is attempted on the `MappingProxyType` for the key `specialty` when the correct key `speciality` exists. 

Additionally, to ensure `len()` checks still work as intended, this does not actually add any new keys to the dictionary, only overriding the `__getitem__` and `get` behavior.

This should not affect any existing tests or submissions.

Example:
```py
request.scope.get('specialty')
>> RuntimeError: You may be using the wrong spelling for 'speciality'; The correct key name is 'speciality', not 'specialty'.

request.scope['specialty']
>> RuntimeError: You may be using the wrong spelling for 'speciality'; The correct key name is 'speciality', not 'specialty'.
```

2022-06-29 23:05 UTC, Bluenix2 requested changes

2022-06-29 23:32 UTC, ionite34 commented on qualifier/tests.py
> +    )
Implemented in 23bf73b:
> Made error instances individual

2022-06-29 23:33 UTC, ionite34 commented on qualifier/tests.py
> +            return super().get(key, default)
Implemented in 23bf73b:
> Moved wrapper class outside function

2022-06-29 23:33 UTC, ionite34 commented on qualifier/tests.py
> +
Implemented in 23bf73b:
> Removed conditional check and always wraps dict

2022-06-30 01:18 UTC, Bluenix2 approved these changes
Thank you this is working as expected, looks good! I think this will be super helpful.

2022-06-30 01:20 UTC, merged